-- Populate Your Tables Here --
DELETE FROM slug;
INSERT INTO slug (username, email, pass) VALUES ('Molly Member', 'molly@slugmail.com', '$2b$10$Y00XOZD/f5gBSpDusPUgU.iJufk6Nxx6gAoHRG8t2eHyGgoP2bK4y');
INSERT INTO slug (username, email, pass) VALUES ('Anna Admin', 'anna@slugmail.com', '$2b$10$Y00XOZD/f5gBSpDusPUgU.G1ohpR3oQbbBHK4KzX7dU219Pv/lzze');

DELETE FROM mailbox;
INSERT INTO mailbox (owned_by, boxname) VALUES ('molly@slugmail.com', 'Inbox');
INSERT INTO mailbox (owned_by, boxname) VALUES ('anna@slugmail.com', 'Inbox');
INSERT INTO mailbox (owned_by, boxname) VALUES ('molly@slugmail.com', 'Trash');
INSERT INTO mailbox (owned_by, boxname) VALUES ('anna@slugmail.com', 'Trash');
INSERT INTO mailbox (owned_by, boxname) VALUES ('molly@slugmail.com', 'Sent');
INSERT INTO mailbox (owned_by, boxname) VALUES ('anna@slugmail.com', 'Sent');

DELETE FROM mail;
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Fry","email":"futurama@ucsc.edu"},"received":"2022-07-22T23:17:19Z","sent":"2022-07-22T23:17:19Z","content":"This is a message from the future","subject":"The Future"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Kevin Crawford","email":"kemcrawf@ucsc.edu"},"received":"2022-07-21T23:17:19Z","sent":"2022-07-21T23:17:19Z","content":"Good luck passing assignment 8 :)","subject":"頑張って！"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Some Guy","email":"guy@ucsc.edu"},"received":"2022-07-20T23:17:19Z","sent":"2022-07-20T23:17:19Z","content":"Hi this is a really long portion of text that im going to type right here la di da di da.","subject":"Long message"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Hello","email":"hi@ucsc.edu"},"received":"2022-07-10T23:17:19Z","sent":"2022-07-10T23:17:19Z","content":"This is a message!","subject":"Look at this email"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"YOASOBI","email":"jpop@ucsc.edu"},"received":"2022-04-12T23:17:19Z","sent":"2022-04-12T23:17:19Z","content":"騒がしい日々に 笑えない君に思い付く限り眩しい明日を明けない夜に落ちてゆく前に僕の手を掴んでほら忘れてしまいたくて 閉じ込めた日々も抱きしめた温もりで溶かすから怖くないよ いつか日が昇るまで 二人でいよう","subject":"夜に駆ける"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Keanu Reeves","email":"ted@ucsc.edu"},"received":"2021-11-17T23:17:19Z","sent":"2021-11-14T23:17:19Z","content":"Be excellent to each other.","subject":"Bill and Ted"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Keanu Reeves","email":"neo@ucsc.edu"},"received":"2020-11-17T23:17:19Z","sent":"2020-11-14T23:17:19Z","content":"I know kung fu.","subject":"The Matrix"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Anna Admin","email":"anna@slugmail.com"},"from":{"name":"Keanu Reeves","email":"wick@ucsc.edu"},"received":"2021-11-17T23:17:19Z","sent":"2021-11-14T23:17:19Z","content":"Im thinking im back.","subject":"John Wick"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'anna@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Garbage","email":"trash@ucsc.edu"},"received":"2022-06-12T23:17:19Z","sent":"2022-06-12T23:17:19Z","content":"This is a message in your trash","subject":"Trash"}' FROM mailbox WHERE mailbox.boxname = 'Trash' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Mailman","email":"mail@ucsc.edu"},"received":"2020-06-12T23:17:19Z","sent":"2020-06-12T23:17:19Z","content":"How has your day been?","subject":"Hey"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Leonardo DiCaprio","email":"wolf@ucsc.edu"},"received":"2015-06-12T23:17:19Z","sent":"2015-06-12T23:17:19Z","content":"Interested in investing in any startups?","subject":"The Wolf of Wallstreet"}' FROM mailbox WHERE mailbox.boxname = 'Trash' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Bill Gates","email":"microsoft_gates@ucsc.edu"},"received":"2016-06-12T23:17:19Z","sent":"2016-06-12T23:17:19Z","content":"The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency. The second is that automation applied to an inefficient operation will magnify the inefficiency.","subject":"Quote"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Molly Member","email":"molly@slugmail.com"},"from":{"name":"Hal 9000","email":"hal@ucsc.edu"},"received":"2001-06-12T23:17:19Z","sent":"2001-06-12T23:17:19Z","content":"Let me put it this way, Mr. Amor. The 9000 series is the most reliable computer ever made. No 9000 computer has ever made a mistake or distorted information. We are all, by any practical definition of the words, foolproof and incapable of error.","subject":"2001: A Space Odyssey"}' FROM mailbox WHERE mailbox.boxname = 'Inbox' AND mailbox.owned_by = 'molly@slugmail.com';
INSERT INTO mail (id, mail) SELECT mailbox.id, '{"to":{"name":"Anna Admin","email":"anna@slugmail.com"},"from":{"name":"Keanu Reeves","email":"johnny@ucsc.edu"},"received":"2022-07-21T23:17:19Z","sent":"2022-07-21T23:17:19Z","content":"Sometimes life imitates art.","subject":"Cyberpunk 2077"}' FROM mailbox WHERE mailbox.boxname = 'Trash' AND mailbox.owned_by = 'anna@slugmail.com';
